CREATE TABLE measurements (
    measurement_id INTEGER PRIMARY KEY AUTOINCREMENT,
    paper_citation TEXT,
    original_source_citation TEXT,
    source_location TEXT,
    site_description TEXT,
    latitude REAL,
    longitude REAL,
    parameter_name TEXT NOT NULL,
    cas_number TEXT,
    category TEXT,
    matrix TEXT,
    sample_type TEXT,
    time_period TEXT,
    time_granularity TEXT,
    raw_value REAL,
    mean_value REAL,
    std_dev REAL,
    min_value REAL,
    max_value REAL,
    n_observations INTEGER CHECK (n_observations >= 0),
    aggregation_level TEXT,
    limit_qualifier TEXT CHECK (limit_qualifier IN ('<', '>', '=') OR limit_qualifier IS NULL),
    detection_limit REAL,
    unit TEXT,
    notes TEXT
);
